### PR TITLE
pkg/nvme: delete unused code

### PR DESCRIPTION
**Pull request by yogev-lb**
this code is discovery-service code.
it was wrongfully ported to the discovery-client repo when the projects were splitted.

### CODE REVIEW

**Comment by muliby-lb** [comment]
Looks legit. I assume `needsDataOut` added to `tcp_queue.go` is on purpose?
How was this tested?

**Comment by yogev-lb** [comment]
tested by running CI
This code was not invoked so... no changes were done.

as for this method - it is the only one called from this file so i moved it to a different existing file.

**Review by muliby-lb — APPROVED** [review]
Thanks @yogev-lb
I'm fine with merging it

**Comment by muliby-lb** [comment]
@ronen-lb are we in code freeze or can we merge this?

**Pull request merged**
