### PR TITLE
nvmeclient/nvme_client: fix log line to not expect a param

### PR DESCRIPTION
**Pull request by arturm-lb**
Issue: No Ticket

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved logging for connection failures of IO controllers by simplifying the log message format.
  
- **Chores**
	- Streamlined logging calls for better clarity and maintainability.

### CODE REVIEW

**Comment by muliby-lb** [comment]
LGTM

**Comment by arturm-lb** [comment]
PR Check status: failed during build due to "ERROR root Could not find any tests that match any of tag names ['prcheck=discovery']", I see previous PR check from a month ago failed on the same issue.  @muliby-lb, I see that all tests that were marked for the discovery PR check were actually moved to the deprecated tests directory.. I assume thats why they weren't found.. but I can't really find the relevant code that scans for the tags to know if this is the right assumption.. can you please point me to it?

**Comment by muliby-lb** [comment]
> PR Check status: failed during build due to "ERROR root Could not find any tests that match any of tag names ['prcheck=discovery']", I see previous PR check from a month ago failed on the same issue. @muliby-lb, I see that all tests that were marked for the discovery PR check were actually moved to the deprecated tests directory.. I assume thats why they weren't found.. but I can't really find the relevant code that scans for the tags to know if this is the right assumption.. can you please point me to it?

Ugh.
1. It is running in jenkins, most likely. It's amazing that it's still up.
2. @shaharz-lb can we convert this repo to use the new github PR system?
3. @arturm-lb for now you can run a subset of these tests or resurrect the old tests from deprecated, but I try to stick to running test that run in the CI, otherwise they are more likely than not to be broken
```
muli@blackfish ~ $ testtagger.sh -t discovery-client -i allci
coverage=discovery-client:
    -> /home/muli/lightbits/src/systests/racktests/1923_etcd_mTLS_cross_server_connectivity_new_installation.py [CI: sanity]
    -> /home/muli/lightbits/src/systests/racktests/2301_physical_alma_8_installation_sanity.py [CI: weekly (unstable)]
    -> /home/muli/lightbits/src/systests/racktests/239_alma_8_vm_installation_test.py [CI: sanity minisanity]
    -> /home/muli/lightbits/src/systests/racktests/280_monitoring_installation_test.py [CI: nightly monitoring-stack]
    -> /home/muli/lightbits/src/systests/racktests/529_discovery_vm_installation_add_node.py [CI: weekly]
    -> /home/muli/lightbits/src/systests/racktests/609_vm_installation_pull.py [CI: nightly (unstable)]
    -> /home/muli/lightbits/src/systests/racktests/625_vm_installation_add_new_server_to_cluster.py [CI: nightly]
```

**Review by eitan-lb — APPROVED** [review]
LGTM

**Comment by shaharz-lb** [comment]
> > PR Check status: failed during build due to "ERROR root Could not find any tests that match any of tag names ['prcheck=discovery']", I see previous PR check from a month ago failed on the same issue. @muliby-lb, I see that all tests that were marked for the discovery PR check were actually moved to the deprecated tests directory.. I assume thats why they weren't found.. but I can't really find the relevant code that scans for the tags to know if this is the right assumption.. can you please point me to it?
> 
> Ugh.
> 
> 1. It is running in jenkins, most likely. It's amazing that it's still up.
> 2. @shaharz-lb can we convert this repo to use the new github PR system?
> 3. @arturm-lb for now you can run a subset of these tests or resurrect the old tests from deprecated, but I try to stick to running test that run in the CI, otherwise they are more likely than not to be broken
> 
> ```
> muli@blackfish ~ $ testtagger.sh -t discovery-client -i allci
> coverage=discovery-client:
>     -> /home/muli/lightbits/src/systests/racktests/1923_etcd_mTLS_cross_server_connectivity_new_installation.py [CI: sanity]
>     -> /home/muli/lightbits/src/systests/racktests/2301_physical_alma_8_installation_sanity.py [CI: weekly (unstable)]
>     -> /home/muli/lightbits/src/systests/racktests/239_alma_8_vm_installation_test.py [CI: sanity minisanity]
>     -> /home/muli/lightbits/src/systests/racktests/280_monitoring_installation_test.py [CI: nightly monitoring-stack]
>     -> /home/muli/lightbits/src/systests/racktests/529_discovery_vm_installation_add_node.py [CI: weekly]
>     -> /home/muli/lightbits/src/systests/racktests/609_vm_installation_pull.py [CI: nightly (unstable)]
>     -> /home/muli/lightbits/src/systests/racktests/625_vm_installation_add_new_server_to_cluster.py [CI: nightly]
> ```

2. Yes. Are we talking about system-tests or Unit tests?

**Comment by muliby-lb** [comment]
> 2. Yes. Are we talking about system-tests or Unit tests?

System tests. Let's start with 239 and 529.

**Comment by shaharz-lb** [comment]
> systests/racktests/529_discovery_vm_installation_add_node.py

I opened a new ticket: [LBM1-34913](https://lightbitslabs.atlassian.net/browse/LBM1-34913)
@elada-lb @maor-lb FYI

**Pull request merged**
