### PR TITLE
Update to go-1.22 and alpine-3.19

### PR DESCRIPTION
**Pull request by majst01**
Hi,

according to: https://go.dev/doc/devel/release, only go 1.20, 1.21 and 1.22 are supported anymore and get security and bug fixes.

alpine 3.16 also nears its end of life: https://endoflife.date/alpine

Update the build to use go-1.22 and Alpine 3.19, also replace all occurrences of `io/ioutil` which is deprecated since go-1.16 with their supported counterparts.

So if you find these enhancements useful, i would appreciate this, because we get challenged on a regular basis for CVEs in the software we deploy to the clusters of our customers.

### CODE REVIEW

**Comment by muliby-lb** [comment]
Thanks @majst01. 
@rahman-lb I know you're busy with openstack at the moment, but let's add this one to the queue as well.
@lev-lb @yogev-lb feel free to chime in if you have any comments.

**Comment by muliby-lb** [comment]
@rahman-lb @lev-lb @yogev-lb ignore the above, I'll take care of the `discovery-client`. I meant to comment on https://github.com/LightBitsLabs/los-csi/pull/37

**Comment by muliby-lb** [comment]
PR check passed. @maor-lb WDYT, can we merge?

**Review by muliby-lb — APPROVED** [review]
PR check passed. Changes look good to me.

**Comment by maor-lb** [comment]
> PR check passed. @maor-lb WDYT, can we merge?

Yeah we should.

**Review by maor-lb — COMMENTED** [review]
@majst01 just one question why did you change all ioutil.TempFile to os.CreateTemp 
Oh understand is deprecated , I didn't know

**Review by maor-lb — APPROVED** [review]

**Comment by majst01** [comment]
> @majst01 just one question why did you change all ioutil.TempFile to os.CreateTemp Oh understand is deprecated , I didn't know

Yes `io/ioutil` is deprecated since go-1.16

**Comment by majst01** [comment]
Thanks

**Comment by muliby-lb** [comment]
> Thanks

Thank you for the patches! The `los-csi` changes will take a bit longer but we'll get them merged as well.

**Pull request merged**
